name: 🤖 Android Builds
on:
  workflow_call:

jobs:
  android:
    runs-on: "ubuntu-20.04"
    name: ${{ matrix.arch }}
    strategy:
      fail-fast: false
      matrix:
        arch: ["x86_64-linux-android", "aarch64-linux-android", "i686-linux-android", "armv7-linux-androideabi"]
       
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      
      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r23c
      - name: Install Cargo NDK
        shell: sh
        run: |
          rustup toolchain install nightly
          rustup override set nightly
          rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
          #cargo install cargo-ndk
      - name: Build share libraries
        shell: sh
        run: |
          rustup target add armv7-linux-androideabi
          rustup target add aarch64-linux-android
          #cargo +nightly ndk -t armeabi-v7a -t arm64-v8a -o ./jniLibs build --release
      - name: Build
        uses: ./.github/actions/build
        with:
          arch: ${{ matrix.arch }}
      - name: Copy to bin
        shell: sh
        run: |
          mv target/release/librust_syntax.so demo/addons/rust-syntax/bin/librust_syntax.android.so
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: rust-syntax-${{ matrix.arch}}
          path: |
            demo/**/*.so
          if-no-files-found: error
