name: 🔗 Builds
on: 
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  static-checks:
    name: 📊 Static checks
    uses: ./.github/workflows/static_checks.yml

  #android-build:
  #  name: 🤖 Android
  #  needs: static-checks
  #  uses: ./.github/workflows/android_builds.yml

  ios-build:
    name: 🍏 iOS
    needs: static-checks
    uses: ./.github/workflows/ios_builds.yml

  linux-build:
    name: 🐧 Linux
    needs: static-checks
    uses: ./.github/workflows/linux_builds.yml

  macos-build:
    name: 🍎 macOS
    needs: static-checks
    uses: ./.github/workflows/macos_builds.yml
    secrets: inherit

  windows-build:
    name: 🏁 Windows
    needs: static-checks
    uses: ./.github/workflows/windows_builds.yml

  godot-build:
    name:  Godot
    uses: ./.github/workflows/godot_builds.yml

  web-build:
    name: 🌐 Web Builds
    needs: static-checks
    uses: ./.github/workflows/web_builds.yml

  merge:
    runs-on: ubuntu-latest
    name: Merge
    #needs: [android-build, ios-build, linux-build, macos-build, windows-build, godot-build, web-build]
    needs: [ios-build, linux-build, macos-build, windows-build, godot-build, web-build]
    steps:
      - uses: actions/upload-artifact/merge@v4
        with:
          name: rust-syntax
          pattern: rust-syntax-*

  release:
    name: Create Release
    permissions:
      contents: write
    needs: [merge]
    uses: ./.github/workflows/release.yml
