name: 🏁 Windows Builds
on:
  workflow_call:

jobs:
  build-windows:
    runs-on: "windows-latest"
    name: ${{ matrix.arch }}
    strategy:
      fail-fast: false
      matrix:
        arch: ["x86_64-pc-windows-msvc", "i686-pc-windows-msvc"]

    steps:
      - uses: actions/checkout@v4
      - name: Build
        uses: ./.github/actions/build
        with:
          arch: ${{ matrix.arch }}
      - name: Copy to bin
        shell: sh
        run: |
          ls target/release
          mv target/release/rust_syntax.dll demo/addons/rust-syntax/bin/librust_syntax.windows.${{ matrix.arch }}.dll
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: rust-syntax-${{ matrix.arch }}
          path: |
            demo/**/*.dll
          if-no-files-found: error
